In [1]:
import mysql.connector
from mysql.connector import errorcode


import pandas as pd
import numpy as np

In [2]:
try:
  cnx = mysql.connector.connect(user='root', password='AlumnaAdalab',
                              host='127.0.0.1', database = 'northwindmysql')
  print("Conexion establecida")

except mysql.connector.Error as err:

  if err.errno == errorcode.ER_ACCESS_DENIED_ERROR:
    print("Something is wrong with your user name or password")
  
  elif err.errno == errorcode.ER_BAD_DB_ERROR:
    print("Database does not exist")
  
  else:
    print(err)

Conexion establecida

In [41]:
cnx = mysql.connector.connect(user='root', password='AlumnaAdalab',
                              host='127.0.0.1', database = 'information_schema')

mycursor = cnx.cursor()

try:
    consulta = "SELECT column_name FROM information_schema.columns WHERE table_schema = 'northwindmysql' and table_name = 'customers'"
    mycursor.execute(consulta)
    print(mycursor)
except mysql.connector.Error as err:
    print(err)
    print("Error Code:", err.errno)
    print("SQLSTATE", err.sqlstate)
    print("Message", err.msg)

MySQLCursor: SELECT column_name FROM information_sche..

In [42]:
for x in mycursor:
    print(x[0])

customer_id
company_name
contact_name
contact_title
address
city
region
postal_code
country
phone
fax

In [14]:
cnx = mysql.connector.connect(user='root', password='AlumnaAdalab',
                              host='127.0.0.1', database = 'northwindmysql')

mycursor = cnx.cursor()

try:
    consulta = "SELECT * FROM customers WHERE country = 'USA' OR country = 'Germany'"
    mycursor.execute(consulta)
    resultado = mycursor.fetchall()

    for x in resultado:
        print(x)
except mysql.connector.Error as err:
    print(err)
    print("Error Code:", err.errno)
    print("SQLSTATE", err.sqlstate)
    print("Message", err.msg)

('ALFKI', 'Alfreds Futterkiste', 'Maria Anders', 'Sales Representative', 'Obere Str. 57', 'Berlin', '', '12209', 'Germany', '030-0074321', '030-0076545')
('BLAUS', 'Blauer See Delikatessen', 'Hanna Moos', 'Sales Representative', 'Forsterstr. 57', 'Mannheim', '', '68306', 'Germany', '0621-08460', '0621-08924')
('DRACD', 'Drachenblut Delikatessen', 'Sven Ottlieb', 'Order Administrator', 'Walserweg 21', 'Aachen', '', '52066', 'Germany', '0241-039123', '0241-059428')
('FRANK', 'Frankenversand', 'Peter Franken', 'Marketing Manager', 'Berliner Platz 43', 'M?nchen', '', '80805', 'Germany', '089-0877310', '089-0877451')
('GREAL', 'Great Lakes Food Market', 'Howard Snyder', 'Marketing Manager', '2732 Baker Blvd.', 'Eugene', 'OR', '97403', 'USA', '(503) 555-7555', '')
('HUNGC', 'Hungry Coyote Import Store', 'Yoshi Latimer', 'Sales Representative', 'City Center Plaza 516 Main St.', 'Elgin', 'OR', '97827', 'USA', '(503) 555-6874', '(503) 555-2376')
('KOENE', 'K?niglich Essen', 'Philip Cramer', 'Sales Associate', 'Maubelstr. 90', 'Brandenburg', '', '14776', 'Germany', '0555-09876', '')
('LAZYK', 'Lazy K Kountry Store', 'John Steel', 'Marketing Manager', '12 Orchestra Terrace', 'Walla Walla', 'WA', '99362', 'USA', '(509) 555-7969', '(509) 555-6221')
('LEHMS', 'Lehmanns Marktstand', 'Renate Messner', 'Sales Representative', 'Magazinweg 7', 'Frankfurt a.M.', '', '60528', 'Germany', '069-0245984', '069-0245874')
('LETSS', "Let's Stop N Shop", 'Jaime Yorres', 'Owner', '87 Polk St. Suite 5', 'San Francisco', 'CA', '94117', 'USA', '(415) 555-5938', '')
('LONEP', 'Lonesome Pine Restaurant', 'Fran Wilson', 'Sales Manager', '89 Chiaroscuro Rd.', 'Portland', 'OR', '97219', 'USA', '(503) 555-9573', '(503) 555-9646')
('MORGK', 'Morgenstern Gesundkost', 'Alexander Feuer', 'Marketing Assistant', 'Heerstr. 22', 'Leipzig', '', '04179', 'Germany', '0342-023176', '')
('OLDWO', 'Old World Delicatessen', 'Rene Phillips', 'Sales Representative', '2743 Bering St.', 'Anchorage', 'AK', '99508', 'USA', '(907) 555-7584', '(907) 555-2880')
('OTTIK', 'Ottilies K?seladen', 'Henriette Pfalzheim', 'Owner', 'Mehrheimerstr. 369', 'K?ln', '', '50739', 'Germany', '0221-0644327', '0221-0765721')
('QUICK', 'QUICK-Stop', 'Horst Kloss', 'Accounting Manager', 'Taucherstra?e 10', 'Cunewalde', '', '01307', 'Germany', '0372-035188', '')
('RATTC', 'Rattlesnake Canyon Grocery', 'Paula Wilson', 'Assistant Sales Representative', '2817 Milton Dr.', 'Albuquerque', 'NM', '87110', 'USA', '(505) 555-5939', '(505) 555-3620')
('SAVEA', 'Save-a-lot Markets', 'Jose Pavarotti', 'Sales Representative', '187 Suffolk Ln.', 'Boise', 'ID', '83720', 'USA', '(208) 555-8097', '')
('SPLIR', 'Split Rail Beer & Ale', 'Art Braunschweiger', 'Sales Manager', 'P.O. Box 555', 'Lander', 'WY', '82520', 'USA', '(307) 555-4680', '(307) 555-6525')
('THEBI', 'The Big Cheese', 'Liz Nixon', 'Marketing Manager', '89 Jefferson Way Suite 2', 'Portland', 'OR', '97201', 'USA', '(503) 555-3612', '')
('THECR', 'The Cracker Box', 'Liu Wong', 'Marketing Assistant', '55 Grizzly Peak Rd.', 'Butte', 'MT', '59801', 'USA', '(406) 555-5834', '(406) 555-8083')
('TOMSP', 'Toms Spezialit?ten', 'Karin Josephs', 'Marketing Manager', 'Luisenstr. 48', 'M?nster', '', '44087', 'Germany', '0251-031259', '0251-035695')
('TRAIH', "Trail's Head Gourmet Provisioners", 'Helvetius Nagy', 'Sales Associate', '722 DaVinci Blvd.', 'Kirkland', 'WA', '98034', 'USA', '(206) 555-8257', '(206) 555-2174')
('WANDK', 'Die Wandernde Kuh', 'Rita M?ller', 'Sales Representative', 'Adenauerallee 900', 'Stuttgart', '', '70563', 'Germany', '0711-020361', '0711-035428')
('WHITC', 'White Clover Markets', 'Karl Jablonski', 'Owner', '305 - 14th Ave. S. Suite 3B', 'Seattle', 'WA', '98128', 'USA', '(206) 555-4112', '(206) 555-4115')

In [19]:
df = pd.DataFrame(resultado, columns = ["customer_id", "company_name", "contact_name", "contact_title", "adrdress", "city", "regi√≥n", "postal_code", "country", "phone", "fax"])
df.head(10)

,customer_id,company_name,contact_name,contact_title,adrdress,city,regi√≥n,postal_code,country,phone,fax
0,ALFKI,Alfreds Futterkiste,Maria Anders,Sales Representative,Obere Str. 57,Berlin,,12209,Germany,030-0074321,030-0076545
1,BLAUS,Blauer See Delikatessen,Hanna Moos,Sales Representative,Forsterstr. 57,Mannheim,,68306,Germany,0621-08460,0621-08924
2,DRACD,Drachenblut Delikatessen,Sven Ottlieb,Order Administrator,Walserweg 21,Aachen,,52066,Germany,0241-039123,0241-059428
3,FRANK,Frankenversand,Peter Franken,Marketing Manager,Berliner Platz 43,M?nchen,,80805,Germany,089-0877310,089-0877451
4,GREAL,Great Lakes Food Market,Howard Snyder,Marketing Manager,2732 Baker Blvd.,Eugene,OR,97403,USA,(503) 555-7555,
5,HUNGC,Hungry Coyote Import Store,Yoshi Latimer,Sales Representative,City Center Plaza 516 Main St.,Elgin,OR,97827,USA,(503) 555-6874,(503) 555-2376
6,KOENE,K?niglich Essen,Philip Cramer,Sales Associate,Maubelstr. 90,Brandenburg,,14776,Germany,0555-09876,
7,LAZYK,Lazy K Kountry Store,John Steel,Marketing Manager,12 Orchestra Terrace,Walla Walla,WA,99362,USA,(509) 555-7969,(509) 555-6221
8,LEHMS,Lehmanns Marktstand,Renate Messner,Sales Representative,Magazinweg 7,Frankfurt a.M.,,60528,Germany,069-0245984,069-0245874
9,LETSS,Let's Stop N Shop,Jaime Yorres,Owner,87 Polk St. Suite 5,San Francisco,CA,94117,USA,(415) 555-5938,

In [20]:
df.tail(10)

,customer_id,company_name,contact_name,contact_title,adrdress,city,regi√≥n,postal_code,country,phone,fax
14,QUICK,QUICK-Stop,Horst Kloss,Accounting Manager,Taucherstra?e 10,Cunewalde,,01307,Germany,0372-035188,
15,RATTC,Rattlesnake Canyon Grocery,Paula Wilson,Assistant Sales Representative,2817 Milton Dr.,Albuquerque,NM,87110,USA,(505) 555-5939,(505) 555-3620
16,SAVEA,Save-a-lot Markets,Jose Pavarotti,Sales Representative,187 Suffolk Ln.,Boise,ID,83720,USA,(208) 555-8097,
17,SPLIR,Split Rail Beer & Ale,Art Braunschweiger,Sales Manager,P.O. Box 555,Lander,WY,82520,USA,(307) 555-4680,(307) 555-6525
18,THEBI,The Big Cheese,Liz Nixon,Marketing Manager,89 Jefferson Way Suite 2,Portland,OR,97201,USA,(503) 555-3612,
19,THECR,The Cracker Box,Liu Wong,Marketing Assistant,55 Grizzly Peak Rd.,Butte,MT,59801,USA,(406) 555-5834,(406) 555-8083
20,TOMSP,Toms Spezialit?ten,Karin Josephs,Marketing Manager,Luisenstr. 48,M?nster,,44087,Germany,0251-031259,0251-035695
21,TRAIH,Trail's Head Gourmet Provisioners,Helvetius Nagy,Sales Associate,722 DaVinci Blvd.,Kirkland,WA,98034,USA,(206) 555-8257,(206) 555-2174
22,WANDK,Die Wandernde Kuh,Rita M?ller,Sales Representative,Adenauerallee 900,Stuttgart,,70563,Germany,0711-020361,0711-035428
23,WHITC,White Clover Markets,Karl Jablonski,Owner,305 - 14th Ave. S. Suite 3B,Seattle,WA,98128,USA,(206) 555-4112,(206) 555-4115

In [21]:
df.sample(5)

,customer_id,company_name,contact_name,contact_title,adrdress,city,regi√≥n,postal_code,country,phone,fax
17,SPLIR,Split Rail Beer & Ale,Art Braunschweiger,Sales Manager,P.O. Box 555,Lander,WY,82520,USA,(307) 555-4680,(307) 555-6525
14,QUICK,QUICK-Stop,Horst Kloss,Accounting Manager,Taucherstra?e 10,Cunewalde,,01307,Germany,0372-035188,
19,THECR,The Cracker Box,Liu Wong,Marketing Assistant,55 Grizzly Peak Rd.,Butte,MT,59801,USA,(406) 555-5834,(406) 555-8083
12,OLDWO,Old World Delicatessen,Rene Phillips,Sales Representative,2743 Bering St.,Anchorage,AK,99508,USA,(907) 555-7584,(907) 555-2880
11,MORGK,Morgenstern Gesundkost,Alexander Feuer,Marketing Assistant,Heerstr. 22,Leipzig,,04179,Germany,0342-023176,

In [22]:
df.isnull().sum()

customer_id      0
company_name     0
contact_name     0
contact_title    0
adrdress         0
city             0
regi√≥n           0
postal_code      0
country          0
phone            0
fax              0
dtype: int64

In [26]:
df.describe()

,customer_id,company_name,contact_name,contact_title,adrdress,city,regi√≥n,postal_code,country,phone,fax
count,24,24,24,24,24,24,24,24,24,24,24
unique,24,24,24,9,24,23,9,24,2,24,18
top,ALFKI,Alfreds Futterkiste,Maria Anders,Sales Representative,Obere Str. 57,Portland,,12209,USA,030-0074321,
freq,1,1,1,7,1,2,11,1,13,1,7

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    24 non-null     object
 1   company_name   24 non-null     object
 2   contact_name   24 non-null     object
 3   contact_title  24 non-null     object
 4   adrdress       24 non-null     object
 5   city           24 non-null     object
 6   regi√≥n         24 non-null     object
 7   postal_code    24 non-null     object
 8   country        24 non-null     object
 9   phone          24 non-null     object
 10  fax            24 non-null     object
dtypes: object(11)
memory usage: 2.2+ KB

In [27]:
df.columns

Index(['customer_id', 'company_name', 'contact_name', 'contact_title',
       'adrdress', 'city', 'regi√≥n', 'postal_code', 'country', 'phone', 'fax'],
      dtype='object')